
export const IS_LOADING = 'IS_LOADING'
export const IS_BTN_DISABLED = 'IS_BTN_DISABLED'
export const CATEGORIES_LOADED = 'CATEGORIES_LOADED'
export const PRODUCTS_LOADED = 'PRODUCTS_LOADED'
export const PRODUCTS_COUNTED = 'PRODUCTS_COUNTED'
export const PRODUCTS_AVAILABILITY_LOADED = 'PRODUCTS_AVAILABILITY_LOADED'
export const SPECIFIC_PRODUCT_FETCHED = 'SPECIFIC_PRODUCT_FETCHED'